# Generated by Django 5.2.5 on 2025-08-12 06:15

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vitalslog',
            name='blood_pressure',
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(choices=[('DOCTOR', 'Doctor Visit'), ('THERAPY', 'Physical Therapy'), ('LAB', 'Lab Work'), ('SPECIALIST', 'Specialist Consultation'), ('FOLLOW_UP', 'Follow-up'), ('OTHER', 'Other')], default='DOCTOR', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='appointment',
            name='duration',
            field=models.IntegerField(default=30, help_text='Duration in minutes'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('RESCHEDULED', 'Rescheduled')], default='SCHEDULED', max_length=20),
        ),
        migrations.AddField(
            model_name='caretask',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caretask',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='caretask',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caretask',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caretask',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='caretask',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=20),
        ),
        migrations.AddField(
            model_name='caretask',
            name='task_type',
            field=models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('ONE_TIME', 'One Time'), ('CUSTOM', 'Custom')], default='DAILY', max_length=20),
        ),
        migrations.AddField(
            model_name='caretask',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='elderprofile',
            name='allergies',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='elderprofile',
            name='blood_type',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='elderprofile',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='elderprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='elderprofile',
            name='emergency_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='elderprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1),
        ),
        migrations.AddField(
            model_name='elderprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='elderprofile',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='phone_2',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='actions_taken',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='follow_up_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='follow_up_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='incident_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='incident_type',
            field=models.CharField(choices=[('FALL', 'Fall'), ('MEDICATION_ERROR', 'Medication Error'), ('INJURY', 'Injury'), ('ILLNESS', 'Illness'), ('BEHAVIORAL', 'Behavioral Issue'), ('EQUIPMENT', 'Equipment Failure'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_incidents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='resolved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='witnesses',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='medication',
            name='medication_type',
            field=models.CharField(choices=[('PILL', 'Pill'), ('LIQUID', 'Liquid'), ('INJECTION', 'Injection'), ('INHALER', 'Inhaler'), ('TOPICAL', 'Topical'), ('OTHER', 'Other')], default='PILL', max_length=20),
        ),
        migrations.AddField(
            model_name='medication',
            name='strength',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='medicationschedule',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicationschedule',
            name='instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medicationschedule',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='medicationschedule',
            name='time_1',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicationschedule',
            name='time_2',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicationschedule',
            name='time_3',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('MEDICATION', 'Medication Reminder'), ('APPOINTMENT', 'Appointment Reminder'), ('TASK', 'Task Reminder'), ('VITALS', 'Vitals Due'), ('INCIDENT', 'Incident Alert'), ('GENERAL', 'General')], default='GENERAL', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='read_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='read_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vitalslog',
            name='blood_pressure_diastolic',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(200)]),
        ),
        migrations.AddField(
            model_name='vitalslog',
            name='blood_pressure_systolic',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(300)]),
        ),
        migrations.AddField(
            model_name='vitalslog',
            name='blood_sugar',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(600)]),
        ),
        migrations.AddField(
            model_name='vitalslog',
            name='logged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vitalslog',
            name='oxygen_saturation',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(70), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='vitalslog',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='elder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='care_app.elderprofile'),
        ),
        migrations.AlterField(
            model_name='caretask',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='caretask',
            name='elder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_tasks', to='care_app.elderprofile'),
        ),
        migrations.AlterField(
            model_name='caretask',
            name='frequency',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='caretask',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='elder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='care_app.elderprofile'),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='relation',
            field=models.CharField(choices=[('SPOUSE', 'Spouse'), ('CHILD', 'Child'), ('SIBLING', 'Sibling'), ('FRIEND', 'Friend'), ('NEIGHBOR', 'Neighbor'), ('DOCTOR', 'Doctor'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='elder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_reports', to='care_app.elderprofile'),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='severity',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20),
        ),
        migrations.AlterField(
            model_name='medicationschedule',
            name='elder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_schedules', to='care_app.elderprofile'),
        ),
        migrations.AlterField(
            model_name='medicationschedule',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicationschedule',
            name='frequency',
            field=models.CharField(choices=[('DAILY', 'Daily'), ('TWICE_DAILY', 'Twice Daily'), ('THRICE_DAILY', 'Three Times Daily'), ('WEEKLY', 'Weekly'), ('AS_NEEDED', 'As Needed'), ('CUSTOM', 'Custom')], default='DAILY', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='elder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='care_app.elderprofile'),
        ),
        migrations.AlterField(
            model_name='vitalslog',
            name='elder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals_logs', to='care_app.elderprofile'),
        ),
        migrations.AlterField(
            model_name='vitalslog',
            name='heart_rate',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(200)]),
        ),
        migrations.AlterField(
            model_name='vitalslog',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(90.0), django.core.validators.MaxValueValidator(110.0)]),
        ),
        migrations.CreateModel(
            name='MedicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taken_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('was_skipped', models.BooleanField(default=False)),
                ('skip_reason', models.TextField(blank=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='care_app.medicationschedule')),
                ('taken_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('ADMIN', 'Administrator'), ('CAREGIVER', 'Caregiver'), ('GUARDIAN', 'Guardian'), ('NURSE', 'Nurse'), ('DOCTOR', 'Doctor')], default='CAREGIVER', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=100)),
                ('emergency_phone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
