# Generated by Django 5.2.5 on 2025-08-16 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_app', '0003_fix_model_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elderprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
