# Generated by Django 5.2.5 on 2025-08-20 16:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_app', '0005_add_emergency_contact_audit_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencycontact',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
